language: python
python:
  - "3.9"
# command to install dependencies
install:
  - "pip install ."
addons:
  sonarcloud:
    organization: "thefantasyclub-github"
    token:
      secure: SONARQUBE_VALUE
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
